### ISSUE TITLE
Command not found?

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [Kandru/ts3proxy#13]
Good morning!

I am attempting to install this script on my VPS but unfortunately when I "install" via the provided script, it does not create the runnable command. 

I have ensured:
python3 is installed
pip is installed
setup actually runs
I am a non-root user
no errors were received during the collection of the packages, the execution of pip, etc.

Is there anything I am missing?

**Comment by derkalle4** [comment]
Hi,

anyway this is quite old.. but without further command line output when starting the proxy I will not be able to help you.
