### ISSUE TITLE
autostart service

### ISSUE THREAD

**Issue by yousufkhan7feb** [Kandru/ts3proxy#17]
how can I make autostart service

**Comment by derkalle4** [comment]
Hi @yousufkhan7feb ,

this highly depends on the operating system you are using. We generally cannot give advice on how to implement this. However, this is a standard python tool and anything in google like "python3 run as service on <OperatingSystem>" should give you a good hint on how to implement this. However, if you give me your operating system this shoud run on, I may can help you.

**Comment by derkalle4** [comment]
Closing issue due to no response.
