### ISSUE TITLE
Generate config instead of deploying

### ISSUE THREAD

**Issue by Bluscream** [Kandru/ts3proxy#2]
Provide a first-time setup in case the config couldn't be located that will guide the user through the setup process.
This also prevents resetting your config after doing `git pull`

I can PR something like that if you want :)

**Comment by derkalle4** [comment]
I think there is no need for a first-time setup because the config is very easy to edit and save in case of an update. git pull will also be able to merge.

**Comment by Bluscream** [comment]
Git pull failed to merge it for me :/

P.S. https://github.com/Bluscream/pyTSon_plugins/blob/master/ISPValidator/__init__.py#L34

**Comment by derkalle4** [comment]
okay.. but I don't think we need to invest much time into this because the config file won't change that often. ts3proxy shouldn't get to big around that "proxy" stuff. It's mainly a proxy for advanced users not a toy for beginners ;)

**Comment by AlexElvers** [comment]
I also think that merging the `config.yml` would be complicated. What do you think about a `config.example.yml` that the user has to copy to `config.yml` or that is copied automatically to `config.yml` in the working directory?

In the latter case, the `config.example.yml` had to be in the package dir.

**Comment by Bluscream** [comment]
> What do you think about a config.example.yml that the user has to copy to config.yml or that is copied automatically to config.yml in the working directory?

That + nano config.yml could be part of the setup.sh then yes :)

**Comment by derkalle4** [comment]
okay would be an idea. Pls keep it as simple as possible. Someone wan't to make a pull request? Won't have time for working on that today/tomorrow.

**Comment by AlexElvers** [comment]
I rather would use $EDITOR than just nano or ask the user for the preferred editor (default nano).

**Comment by AlexElvers** [comment]
And of course, if the config is copied only in setup.sh, we don't need to have `config.example.yml` in the package dir. We would only need it if the config should be created out of an installed ts3proxy.

**Comment by Bluscream** [comment]
$EDITOR is a global var that resolves to the default editor?

**Comment by AlexElvers** [comment]
Correct, but it can also be missing. Can be used by:

```bash
"${EDITOR:-nano}" config.yml
```

**Comment by Bluscream** [comment]
Hmm lets see xD https://github.com/Kandru/ts3proxy/pull/4

**Comment by Bluscream** [comment]
Should we also add
```bash
apt-get install -y python3 python3-yaml
```

**Comment by AlexElvers** [comment]
Definitely not. `apt-get` is Debian-specific.

**Comment by Bluscream** [comment]
Well okay then

**Comment by derkalle4** [comment]
This would be nice in the README of course. But then it would be even nicer if there would be installation methods for multiple linux distributions. Otherwise it wouldn't make any sense. But I can only repeat what I've said earlier: this tool is not for rookies. It's for advanced users. A normal user with a hosted teamspeak server wouldn't need this tool. So hopefully only people who know how to administrate an own server will install and use this script ;) and they should actually know how to use the package manager of their distribution.
