### ISSUE TITLE
Proxy not starting

### ISSUE THREAD

**Issue by Jofkos** [Kandru/ts3proxy#5]
For some reason the proxy doesn't want to start on my linux machine (Debian 8).
Python 3.4.2

```
[2017-09-14 22:15:08,601] Voice: 0.0.0.0:9987 <-> my.target.ip:9987
Traceback (most recent call last):
  File "/usr/local/bin/ts3proxy", line 9, in <module>
    load_entry_point('ts3proxy==0.3', 'console_scripts', 'ts3proxy')()
  File "/home/ts3proxy/ts3proxy/ts3proxy.py", line 48, in main
    file_transfer = TcpRelay.create_from_config(logging, config['ts3FileTransfer'])
  File "/home/ts3proxy/ts3proxy/tcp.py", line 103, in create_from_config
    whitelist_file=relay_config['whitelist'],
  File "/home/ts3proxy/ts3proxy/tcp.py", line 22, in __init__
    self.socket.listen()
TypeError: listen() takes exactly one argument (0 given)`

Is there something I can do wrong?

**Comment by AlexElvers** [comment]
The Python 3 documentation states:

> socket.listen([backlog])
> Changed in version 3.5: The backlog parameter is now optional.

see https://docs.python.org/3/library/socket.html#socket.socket.listen

You can either update to a newer version of Python (the most recent is 3.6) or simply add the backlog parameter.

**Comment by Jofkos** [comment]
Thank you. I thought I did something wrong, but added the backlog parameter fixed it. 👍

**Comment by Bluscream** [comment]
I had the same problem i had to update from jessie to stretch and install https://github.com/chriskuehl/python3.6-debian-stretch
