### ISSUE TITLE
Multiple TS3 Servers

### ISSUE THREAD

**Issue by Jniklas2** [Kandru/ts3proxy#6]
Sorry for my bad english

Is there a way to add more than one TS3 Server or can I only proxy one server at a time?

**Comment by derkalle4** [comment]
Hey @Jniklas2 it's no problem to have more then one TS3 server. Only impossible thing is to have multiple instances of the filetransfer and server query. Filetransfer and server query will still work fine if you have one host instance of a TS3 server and multiple virtual server. You can easily add every virtual server instance into the config (see example in config file):

```
# relayPort:remoteAddress:remotePort
# multiple servers splitted by ","
  servers: "9987:master_ts3_ip_here:9987,9988:master_ts3_ip_here:9988,9977:master_ts3_ip_here:9977"
```

Hopefully that answered your question.

**Comment by derkalle4** [comment]
Closing question because there was no answer for more then 27 days.

**Comment by Bluscream** [comment]
Can you also start a new Weblist() instance for each redirect?
Or maybe to improve perfomance just initiate it once and let it send weblist requests for each redirect every 10 mins
