### ISSUE TITLE
Allow portranges

### ISSUE THREAD

**Issue by Bluscream** [Kandru/ts3proxy#7]
For example: `servers: "1-65535:127.0.0.1:9987"` and it will take as many ports as it can from that range (show an error for ports that are in use)

**Comment by derkalle4** [comment]
If you spawn that much sockets on the server the script might goes crazy. Nevermind your problem can easily get fixed with iptables :)

Please look here:

https://superuser.com/questions/440324/iptables-how-to-forward-all-external-ports-to-one-local-port

**Comment by Bluscream** [comment]
Outsourcing to another software is not really an answer but you could just tell me "don't use my software then" ..

**Comment by Bluscream** [comment]
Also i was wondering if i should PR a IPTables mode in which the proxy itself would just manage iptable rules for the tunneling.

I was also thinking about a more advanced query connection to for example auto tunnel new virtual servers or disable tunneling for offline or "online virtual" servers.

**Comment by derkalle4** [comment]
It's not about "don't use my software then". You simply did not understand what I wanted to state. The script is Open Source and you have already forked it. Then go ahead and "use your software then". You can try sth like this: https://stackoverflow.com/questions/47363055/python-socket-listen-on-all-ports

It is always easier to use a software that is designed for that kind of thing. And IPTables as firewall clearly is. I mean: you would not use a car to open a bottle, would you?

The second would be an optional idea but at the moment I think it's enough to just configure the software one time and do a change if somebody is changing something on his server. I think it's better to stick to the roots. But if you want to add sth like this feel free to use your already created fork and I'll test it and then decide wether to push it into the master repo or not.

**Comment by Bluscream** [comment]
Bad example you did there https://lifehacker.com/5951230/open-a-beer-bottle-with-a-car-window :stuck_out_tongue: 

> And IPTables as firewall clearly is

So you say IPTables is better for routing (what this whole app is about)?
